### PR TITLE
Update Almanac for 1.6

### PR DESCRIPTION
**Pull request by Vindeflei**
Updated the Almanac files (and Common files used by Almanac) to work for Stardew 1.6.

### CODE REVIEW

**Comment by Vindeflei** [comment]
Okay, made sure the common.targets file is correct for you, and reverted the changes in SeeMeRollin that must have popped up during the dav-1.6 merge I started with.

**Comment by Vindeflei** [comment]
It is a lot, but I tried my best to work on one section at a time and label my commits well, so hopefully that helps. One of my best friends absolutely adores your Almanac mod, which is why I decided I wanted to try this. I'm also currently going through and adding in the ability to recognize new events in the Notices Manager, since there's a new merchant and new passive festivals. I'll push that up when I finish it tonight or tomorrow.

**Comment by Vindeflei** [comment]
Oh. I was trying to go through and fix the merge conflicts. I didn't realise it would reapply everything, I'm so sorry.

**Comment by Vindeflei** [comment]
I undid the rebase because it broke a bunch of things. Let me know if there's anything else you'd like me to do. I think the Almanac works as intended now, at least for the base game.

**Comment by KhloeLeclair** [comment]
Alright, I'm going to just leave myself a tag before this point, merge everything that's not in Common, and start going.

Thanks for all your work. I'll make sure to credit you in the public change list. I'm not sure how many changes I'll be making, but hopefully I can get out a quick "just an initial it works" 1.6 build.

**Pull request merged**
